name: mubarak_vegetables
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.2
  lottie: ^3.3.1
  cloud_firestore: ^5.6.6
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.1
  geocoding: ^3.0.0
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  carousel_slider: ^5.0.0
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  location: ^8.0.0
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.1.0
  maptiler_flutter: ^0.1.0
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# Add this at the root level, not under dev_dependencies
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"




  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/