// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApSKweWUezdBv_dD8rJLgrRovcJVx4DOU',
    appId: '1:704950380065:web:b63e8a585ea3acc5ede560',
    messagingSenderId: '704950380065',
    projectId: 'mubarak-vegi',
    authDomain: 'mubarak-vegi.firebaseapp.com',
    databaseURL: 'https://mubarak-vegi-default-rtdb.firebaseio.com',
    storageBucket: 'mubarak-vegi.firebasestorage.app',
    measurementId: 'G-N44LGNMN5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tT5uovSUvzCIxm8TV6wvJ0vyTGpmZiQ',
    appId: '1:704950380065:android:b1cc166dd7dc7b89ede560',
    messagingSenderId: '704950380065',
    projectId: 'mubarak-vegi',
    databaseURL: 'https://mubarak-vegi-default-rtdb.firebaseio.com',
    storageBucket: 'mubarak-vegi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUuNFwKaOwIK-Sdxdah4dIwe6jievPYg',
    appId: '1:704950380065:ios:5bdc43f4b24cf36fede560',
    messagingSenderId: '704950380065',
    projectId: 'mubarak-vegi',
    databaseURL: 'https://mubarak-vegi-default-rtdb.firebaseio.com',
    storageBucket: 'mubarak-vegi.firebasestorage.app',
    iosBundleId: 'com.example.mubarakVegetables',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNUuNFwKaOwIK-Sdxdah4dIwe6jievPYg',
    appId: '1:704950380065:ios:5bdc43f4b24cf36fede560',
    messagingSenderId: '704950380065',
    projectId: 'mubarak-vegi',
    databaseURL: 'https://mubarak-vegi-default-rtdb.firebaseio.com',
    storageBucket: 'mubarak-vegi.firebasestorage.app',
    iosBundleId: 'com.example.mubarakVegetables',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApSKweWUezdBv_dD8rJLgrRovcJVx4DOU',
    appId: '1:704950380065:web:19acfaaf690b06ddede560',
    messagingSenderId: '704950380065',
    projectId: 'mubarak-vegi',
    authDomain: 'mubarak-vegi.firebaseapp.com',
    databaseURL: 'https://mubarak-vegi-default-rtdb.firebaseio.com',
    storageBucket: 'mubarak-vegi.firebasestorage.app',
    measurementId: 'G-QVH4VDW3HX',
  );
}
